name: m3pay
description: A digital wallet and payment app based on six_cash
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Core & Utilities ---
  intl: any
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  path_provider: ^2.1.3
  http: ^1.2.2

  # --- Firebase & Notifications ---
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^17.2.3

  # --- UI / Animations / Design ---
  dotted_border: ^2.1.0
  azlistview: ^2.0.0
  pin_code_fields: ^8.0.1
  modal_bottom_sheet: ^3.0.0
  slide_to_confirm: ^1.1.0
  lottie: ^3.1.2
  expandable_bottom_sheet: ^1.1.1+1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  flutter_smart_dialog: ^4.9.6+1

  # --- Image / Media ---
  image_picker: ^1.1.2
  camera: ^0.10.5+9
  screenshot: ^3.0.0
  file_picker: ^8.1.2
  flutter_image_compress: ^2.3.0
  gallery_saver:
    git:
      url: https://github.com/CarnegieTechnologies/gallery_saver.git
      ref: master

  # --- Permissions & Device Info ---
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  unique_identifier: ^0.4.0
  local_auth: ^2.2.0
  app_settings: ^5.1.1

  # --- ML / Barcode / Face Detection ---
  google_mlkit_barcode_scanning: ^0.13.0
  google_mlkit_face_detection: ^0.12.0

  # --- Sharing / Web / Utilities ---
  share_plus: ^10.1.2
  url_launcher: ^6.3.0
  flutter_inappwebview: ^6.0.0
  scroll_to_index: ^3.0.1
  flutter_fgbg: ^0.3.0
  flutter_secure_storage: ^9.0.0
  modal_progress_hud_nsn: ^0.5.1
  phone_numbers_parser: ^9.0.1

  # --- Optional iOS Fix ---
  flutter_inappwebview_ios: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/animationFile/
    - assets/payment/
    - assets/svg/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 600
